version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: 4eredn1koff/foodgram_backend
    env_file: ../.env
    volumes:
      - static_volume:/static
      - media:/app/media
  frontend:
    image: 4eredn1koff/foodgram_frontend
    env_file: ../.env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: 4eredn1koff/foodgram_gateway
    env_file: ../.env
    volumes:
      - static_volume:/staticfiles/
      - media:/media/
    ports:
      - 8080:80
    depends_on:
      - db